port: 3000
JEKYLL_ENV: development
exclude: ['views', 'Gemfile', 'app.rb', 'config.ru', 'README.md', 'Gemfile.lock', 'vendor', 'bin']
include: ['_pages']

permalink: none
show_dir_listing: false

title: The blog of Anna
email: ajwleach@gmail.com
description: Development, personal and otherwise, the blog of Anna Leach.
twitter_username: annajleach
github_username:  ajwl
github: 'https://github.com/ajwl'
excerpt_separator: "<!--excerpt-->"

url: "https://annaleach.herokuapp.com"
image_base: '/images'
baseurl: '/blog'
repository: 'https://github.com/ajwl/ps1'

# Build settings
markdown: kramdown




