exclude: ['views', 'Gemfile', 'app.rb', 'config.ru', 'README.md', 'Gemfile.lock', 'vendor', 'bin']
include: ['_pages']

# Build settings
markdown: kramdown
highlighter: rouge
scope: '.highlight'

permalink: none
show_dir_listing: false

title: The blog of Anna
description: Development, personal and otherwise, the blog of Anna Leach.
github: 'https://github.com/ajwl'
excerpt_separator: "<!--excerpt-->"

url: "https://www.annaleach.net"
image_base: '/images'
baseurl: '/blog'

