port: 3000
JEKYLL_ENV: development
exclude: ['views', 'Gemfile', 'app.rb', 'config.ru', 'README.md', 'Gemfile.lock']
include: ['_pages']

auto: true
server: false
permalink: none

title: The blog of Anna
email: your-email@domain.com
description: Development, personal and otherwise, the blog of Anna Leach.

url: "http://localhost:3000"
image_base: '/images'

twitter_username: annajleach
github_username:  ajwl

# Build settings
markdown: kramdown

show_dir_listing: false
baseurl: '/blog'
