port: 3000
#source: '_posts'
#destination: '_site'
JEKYLL_ENV: development
exclude: ['views', 'Gemfile', 'app.rb', 'config.ru', 'README.md', 'Gemfile.lock']

auto: true
server: false
permalink: none

title: The blog of Anna
email: your-email@domain.com
description: Development, personal and otherwise, the blog of Anna Leach.

url: "http://localhost:3000"
image_base: '/images'

twitter_username: annajleach
github_username:  ajwl

# Build settings
markdown: kramdown

show_dir_listing: false
#host: 127.0.0.1
baseurl: #'/blog' the subpath of your site, e.g. /blog
