source: '/_posts'
destination: '/blog'
JEKYLL_ENV: development

auto: true
server: false
permalink: /:title

title: The blog of Anna
email: your-email@domain.com
description: >
  Development, personal and otherwise, the blog of Anna Leach.

{% if jekyll.environment == "production"}
  url: "http://annaleach.net" # the base hostname & protocol for your site
{% else }
  url: "http://127.0.0.1:4000"
{% end %}

twitter_username: annajleach
github_username:  ajwl

# Build settings
markdown: kramdown
theme: minima
repository: "ajwl/blog"

#Build settings
show_dir_listing: false
host: 127.0.0.1
baseurl: "" # the subpath of your site, e.g. /blog
